language: node_js
node_js:
- node
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: oBErcWCbeQty/L/8iRLViGeHBnA3qXroEfKaDE+18BGRhl+Mp5EtUkN6fDyFoX0iS5kiyAnQPJsTNwYDT7kgZHHFGUEcE5CBLZYr2BN2trB0N3TrFC2/2bUgSJcwkY7WK4KG9tb6M10JbVMx4gLwl5AruHU3IxaViNjaRMM9mvBszj+rRxmRLfVp3mW2GgYq8RH6zO+5r+Ax6BYaEOjQIQfvLlIO5eYtNHys+YtgAsDJ8OMGKbregklvZcFw6wX5LHwqKOSkLwWYZt5v+5f/+v3jfIo8JPlk59oC0kwJynkK64EYyJr7kMZL2EhTpCcr9jYjPtBhRUjDg6TkHN52jjmt2qTb7fDV6rqsKESgPL/9giEMYtATaWhXpYsTEFXKlwGZZpliGsNPjAkL/P10kbThoELXB8Lht44kcwsjFNMDKr9TN0B3FSVJk4u+y69Rxb54Fgop+9IehCdO1ItBFGxAtjZ7DJygV2mJPrHXI0TVaNvMv7U1pq36tcQJy93G9dYYta5FPDTwrQp4TAVEWsQS5iCyfc31Yv4h6IsLBvI6icMPRuqzUt161BeNvoQP2t9DqQCajgmMWiDa+0rzBFjHTUnpEfohWd2JsUV5eKmjyDJ6RXjZjVVlVLpJiV3BA3A3Wtvy0mxrVphw5VFo9YRktnbR6VKLqkhBmiR4fD4=
  app: customer-management-app
